repos:

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        exclude: ^migrations/|/migrations/
        additional_dependencies:
              [
                flake8-quotes,
              ]
